<?php
include 'auth.php';
include 'config.php';
if ($auth == 1) {
}
elseif ($auth == 2) {
  }
else {
echo "<p>You are not allowed to do this!</p>";
die;
}
$configs = shell_exec('ls ' . $direction1 . $_GET['serverid']. '/costmstartparam');
$info  =   explode("\n", $configs);
#$newname = $direction1 . $_GET['serverid']. '/costmstartparam/' . 'default.cfg';
$error = true;
for ($i=0; $i < count($info); $i++) {
if (strcmp($info[$i],'default.cfg') == 0) {
  #shell_exec('mv ' .$direction1 . $_GET['serverid']. '/costmstartparam/' .$info[$i]. ' ' .$direction1 . $_GET['serverid']. '/costmstartparam/' . uniqid(). '.cfg');
  $error = false;
echo "hieeera";
  }
}
if ($error == false) {
    echo "nee";
  }
  elseif ($error == true) {
    file_put_contents ($direction1 . $_GET['serverid']. '/costmstartparam/default.cfg', '_______autogenerated');
    chmod($direction1 . $_GET['serverid']. '/costmstartparam/default.cfg', 0777);
    echo 'file generated';
  }
?>
